### PR TITLE
Update config.toml

### PR DESCRIPTION
**Pull request by JiteshRajput**

### CODE REVIEW

**Comment by alluding** [comment]
☠️

**Comment by visuality1337** [comment]
LMAO

**Comment by imvast** [comment]
😭

**Comment by NuvenProjects** [comment]
if you actually added a working script, i might have purchased your full license, hence you deliberately make this script un-usable, you just lost a potential purchaser to some of you codes.

**Comment by alluding** [comment]
> if you actually added a working script, i might have purchased your full license, hence you deliberately make this script un-usable, you just lost a potential purchaser to some of you codes.

What is bro talking about? 💀

**Comment by NuvenProjects** [comment]
script "free version" just a tactic to lure people to buy the one with the fixes, for instance your Solver and few clever "removed" parts in your code making it a non-starter. Hence you want people to pay for something, but nothing is showing that it is working.

**Comment by alluding** [comment]
> script "free version" just a tactic to lure people to buy the one with the fixes, for instance your Solver and few clever "removed" parts in your code making it a non-starter. Hence you want people to pay for something, but nothing is showing that it is working.

It did work. Why do you think it has so many stars? The thing is, Discord is consistent with updates and patches things, as does Hcaptcha. Pretty much every solver is flagged to begin with, even something like cap monster. The paid version works fine. People aren't just going to release a working version every patch so people on GitHub stop complaining and can skid away.

**Comment by imvast** [comment]
LMAO

**Pull request closed without merging**
